---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
## Dashboard live ##

You can view the dashboard online at https://aghababaei-omid.shinyapps.io/canada_dash/


## From the author##

**Thank you for your interest in my new data visualization project.** There are many great COVID-19 Canada dashboards available online. I have compiled the following list to show some of the dashboards that inspired me to build this one. 

- [The COVID-19 Canada Open Data Working Groups dashboard](https://art-bd.shinyapps.io/covid19canada/) made by [Jean-Paul R. Soucy](https://twitter.com/JPSoucy) and [Isha Berry](https://twitter.com/ishaberry2), two students from my school, DLSPH, at Univerity of Toronto.

- [The Covid19 Italy dashboard](https://github.com/RamiKrispin/italy_dash) by [Rami      Krispin](https://twitter.com/Rami_Krispin). 

- [The Esri Canada COVID-19 Canada dashboard](https://resources-covid19canada.hub.arcgis.com/).

- [The PHAC COVID-19 Canada dashboard](https://experience.arcgis.com/experience/2f1a13ca0b29422f9b34660f0b705043/), **most accurate and reliable** info on Canadian COVID-19 epidemiology data.

- [The Ontario-specific COVID-19 Analysis Website](https://howsmyflattening.ca/#/analysis) which covers detailed Ontario focused analytical information on critical care analysis, health region analysis and testing analysis. This website I believe was also built by a group of University of Toronto students.

- [The Québec provincial COVID-19 dashboard](https://www.inspq.qc.ca/covid-19/donnees).

- [The Alberta provincial COVID-19 dashboard](https://covid19stats.alberta.ca/).
 
Using the four COVID-19 Canada Open Data Working Group's spreadsheets on cases, mortality, recovery and testing at <https://github.com/ishaberry/Covid19Canada>, I created an aggregated Canada COVID-19 daily data. You can view this data on the data page of this dash.


**Acknowledgement**

 - **Data** 
- Canada data used in this dashboard are extracted from the data posted by the COVID-19 Canada Open Data Working Group (https://github.com/ishaberry/Covid19Canada) lead by [Jean-Paul R. Soucy](https://twitter.com/JPSoucy) and [Isha Berry](https://twitter.com/ishaberry2). Since April 1st, the working group collected and reported case and mortality data directly from Public Health Units. Thus, the case and mortality numbers reported may be higher than those from other sources, incuding the Ontario Ministry of Health. We direct readers to their dashboard website, [About the data section](https://art-bd.shinyapps.io/covid19canada/) for details.
        - **We want to express our sincere appreciation to all contributors of the COVID-19 Canada Open Data Working Group.** **Here is a list of contributors we want to pay special tribute to [Isha Berry](https://twitter.com/ishaberry2), [Jean-Paul R. Soucy](https://twitter.com/JPSoucy), [Kamal Acharya](https://twitter.com/Kamalraj_ach), [Gabrielle Brankston](https://twitter.com/GBrankston), [Vinyas Harish](https://twitter.com/VinyasHarish), Kathy Kornas, Thivya Naganathan, Lindsay Obress, [Meghan O'Neill](https://twitter.com/_MeghanONeill), [Tanya Rossi](https://twitter.com/DrTanyaRossi), [Alison Simmons](https://twitter.com/alisonesimmons), [Shelby Sturrock](https://twitter.com/shelbysturrock), Matthew Van Camp, [James E.Wright](https://twitter.com/JWright159) and Wendy Xie.**
    - World data used in this dashboard are from the R package coronavirus developed by **[Rami Krispin](https://github.com/RamiKrispin/coronavirus)** which is generated from the Johns Hopkins University Center for Systems Science and Engineering (JHU CCSE) Coronavirus [website](https://systems.jhu.edu/research/public-health/ncov/).
 - **Dashboard R code**
- I built this dashboard using **Kuan Liu's [github](https://github.com/Kuan-Liu/canada_dash) code** as template.  
 - **Special thanks** to my PI **[Dr. Eleanor Pullenayegum](https://twitter.com/EMPullenayegum)** at [Sickkids](http://www.sickkids.ca/AboutSickKids/Directory/People/P/Eleanor-Pullenayegum-staff-profile.html) for her support! 
    


**Feedbacks**

Please feel free to reach me at omid.aghababaeijazi@sickkids.ca


